<?php

function custom_menu_weights_form_alter(&$form, &$form_state, $form_id) {
	if (isset($form['#node_edit_form']) && $form['#node_edit_form']) {
		if(isset($form['#node']->menu['menu_name']) && $form['#node']->menu['menu_name'] == 'og-menu-single') {
			$form['#submit'][] = 'custom_weight_callback';
		}
	}
}

function custom_weight_callback(&$form, &$form_state) {
	$weight = $form_state['input']['menu']['weight'];
	$nid = $form_state['values']['nid'];
	$form_state['values']['menu']['weight'] = $weight;
}

function custom_menu_weights_node_insert($node) {
	if (isset($node->menu['enabled']) &&  strlen($node->menu['enabled'])) {
		$enabled = $node->menu['enabled'];
		$nid = $node->nid;
		if (isset($nid) && !empty($nid)) {
			db_insert('node_menu_links')
				->fields(array(
			 		'nid' => $nid,
			 		'enabled' => $enabled,
			 		))
			 	->execute();
		}
	}
}

function custom_menu_weights_node_update($node) {
	if (isset($node->menu['enabled']) && strlen($node->menu['enabled'])) {
		$enabled = $node->menu['enabled'];
		$nid = $node->nid;
		$settings = _get_menu_links_settings($nid);
		if($settings == -1) {
			//insert
			db_insert('node_menu_links')
				->fields(array(
			 		'nid' => $nid,
			 		'enabled' => $enabled,
			 		))
			 	->execute();
		} else {
			//update
			db_update('node_menu_links')
			  ->fields(array(
			  	'enabled' => $enabled
			 		))
				->condition('nid', $nid)
				->execute();
		}
	}
}