<?php

  function menu_columns_menu() {
    $items['admin/config/menu_columns'] = array(
    'title' => t('Columns settings'),
    'description' => t('Set the number of items per column'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('set_menu_items_per_column'),
    'access arguments' => array('access theme settings page'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'menu_columns.admin.inc',
  );
    return $items;
  }

?>