<?php
/**
 * @file: Functionality of the module.
 */

/**
 * Implements hook_node_insert.
 */
function group_adder_node_insert($node) {
  
  if ($node->type == 'oa_group') {
    
    $admin_uids_result = db_query(
      "
        SELECT uid
        FROM users_roles
        WHERE rid IN (
          SELECT rid
          FROM role 
          WHERE name = 'impetus admin'
        )
      "     
    )->fetchAll();

    if (!empty($admin_uids_result)) {

      foreach ($admin_uids_result as $user) {
        
        $account = user_load($user->uid);
        og_group(
          'node',
          $node->nid, 
          array(
            'entity type' => 'user',
            'entity' => $account,
            'membership type' => OG_MEMBERSHIP_TYPE_DEFAULT,
          )
        );
      }
    }
  }
}
