<?php
/**
 * @file: Functionality of the module.
 */

/**
 * Implements hook_node_insert.
 */
function group_adder_node_insert($node) {
  
  if ($node->type == 'oa_group') {
    
    // Add site administrator.
    $admin_account = user_load(1);
    og_group(
      'node',
      $node->nid, 
      array(
        'entity type' => 'user',
        'entity' => $admin_account,
        'membership type' => OG_MEMBERSHIP_TYPE_DEFAULT,
      )
    );
    group_adder_grant_group_admin($admin_account, $node);
    
    $admin_uids_result = db_query(
      "
        SELECT uid
        FROM users_roles
        WHERE rid IN (
          SELECT rid
          FROM role 
          WHERE name = 'impetus admin'
          OR name = 'administrator'
        )
      "     
    )->fetchAll();

    if (!empty($admin_uids_result)) {      
      
      // Add all admins and impetus admins
      foreach ($admin_uids_result as $user) {
        
        $account = user_load($user->uid);
        og_group(
          'node',
          $node->nid, 
          array(
            'entity type' => 'user',
            'entity' => $account,
            'membership type' => OG_MEMBERSHIP_TYPE_DEFAULT,
          )
        );
        
        group_adder_grant_group_admin($user, $node);
      }
    }
  }
}

/**
 * Helper function.
 * Assigns a user the administrator role to a group.
 * @param object $user: A user object.
 * @param object $group_node: A node object with the bundle type 'oa_group'.
 */
function group_adder_grant_group_admin($user, $group_node) {
  
  $og_roles = og_roles('node', 'oa_group', $group_node->nid, FALSE, FALSE);
  $rid = array_search(OG_ADMINISTRATOR_ROLE, $og_roles);
  
  if ($rid > 0) {
    og_role_grant('node', $group_node->nid, $user->uid, $rid);
    og_invalidate_cache();

  }
}
