<?php
/**
 * @file: Functionality of the module.
 */

module_load_include('inc', 'bulk_file_upload', 'bulk_file_upload.forms');

/**
 * Implements hook_menu_alter.
 */
/*function bulk_file_upload_menu_alter(&$items) {
  
  if (isset($items['node/add/file'])) {
    $items['node/add/file']['access callback'] = 'bulk_file_upload_access_file_pages';
  }
  if (isset($items['node/%/edit'])) {
    kpr($items['node/%/edit']);
    var_dump($items['node/%/edit']);
    exit();
  }
}

function bulk_file_upload_access_file_pages() {
  
  global $user;
  $access = FALSE;
  
  if ($user->uid != 0) {
    $access = TRUE;
  }
  
  return $access;
}

//function bulk_file_upload_form_alter(&$form, &$form_state, $form_id) {
  
//  global $user;
  
//  if ($form_id == 'file_node_form' && $user->uid != 0) {
//    drupal_add_http_header('status', 404);
//    exit();
//  }
//}
 * 
 */

/**
 * Implements hook_ctools_plugin_directory.
 */
function bulk_file_upload_ctools_plugin_directory($owner, $plugin_type) {
  
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_menu.
 */
function bulk_file_upload_menu() {
  
  return array(
    'bulk-download-files' => array(
      'title' => t('Bulk Download Files'),
      'description' => t('Provides the ability to bulk download files as a zip.'),
      'page callback' => 'bulk_file_upload_render_download_page',
      'access callback' => 'user_access',
      'access arguments' => array('bulk download file archive'),
      'file' => 'bulk_file_upload.pages.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Usort implementation.
 * Meant to the result of the taxonomy_get_children function.
 */
function bulk_file_upload_sort_child_folders($a, $b) {
  return strcmp($a->name, $b->name);
}

/**
 * Implements template_preprocess_taxonomy_term.
 */
function bulk_file_upload_preprocess_taxonomy_term(&$variables) {
  
  if ($variables['vocabulary_machine_name'] == 'file_categories') {
    
    // Setting up markup.
    $variables['content']['bulk_file_uploads'] = array(
      '#type' => 'markup',
      '#markup' => '',
    );
    
    $variables['content']['bulk_file_uploads']['#markup'] .= //bulk_file_upload_render_child_folders($variables['term']->tid) .
      bulk_file_upload_render_file_table($variables['term']->tid) .
      render(drupal_get_form('bulk_file_upload_add_taxonomy_term_form', $variables['term']->tid)) .
      render(drupal_get_form('bulk_file_upload_add_files_form', $variables['term']->tid));
  }
}

/**
 * Implements hook_page_build.
 */
function bulk_file_upload_page_build(&$page) {
  
  drupal_add_css(drupal_get_path('module', 'bulk_file_upload') . '/css/bulk_file_upload_general.css');
  
  // Modifying taxonomy term pages for file categories.
  if (arg(0)=='taxonomy' && arg(1)=='term') {
    $term = taxonomy_term_load(arg(2));
    
    if ($term->vocabulary_machine_name == 'file_categories') {
      
      // Setting up content.
      if (isset($page['content']['system_main']['nodes'])) {
        unset($page['content']['system_main']['nodes']);
      }
      
      // Setting up breadcrumb.
      bulk_file_upload_update_breakcrumb_on_taxonomy_page($term);
      
      if (!isset($page['content']['#prefix'])) {
        $page['content']['#prefix'] = bulk_file_upload_render_file_breadcrumb();
      }
      else {
        $page['content']['#prefix'] .= bulk_file_upload_render_file_breadcrumb();
      }
    }
  }
  // Modifying file nodes.
  else if (arg(0) == 'node') {
    $current_node = node_load(arg(1));

    if ($current_node !== FALSE && $current_node->type == 'file') {
      
      // Setting up breadcrumb.
      if (!isset($page['content']['#prefix'])) {
        $page['content']['#prefix'] = bulk_file_upload_render_file_breadcrumb();
      }
      else {
        $page['content']['#prefix'] .= bulk_file_upload_render_file_breadcrumb();
      }
    }
    
  }
}

/**
 * Implements hook_permission.
 */
function bulk_file_upload_permission() {
  return array(
    'access bulk upload page' => array(
      'title' => t('Access bulk upload form'),
    ),
    'access folder add form' => array(
      'title' => t('Access the folder add form'),
    ),
    'bulk download file archive' => array(
      'title' => t('Download all files in a folder as zip'),
    ),
  );
}

/**
 * Implements hook_form_alter.
 */
function bulk_file_upload_form_alter(&$form, &$form_state, $form_id) {
  
  if ($form_id == 'file_node_form') {
    drupal_add_js(drupal_get_path('module', 'bulk_file_upload') . '/js/bulk_file_upload_node_page.js');
  }
}

/**
 * Implements hook_forms.
 */
function bulk_file_upload_forms($form_id, $args) {
  
  return array(
    'bulk_upload_taxonomy_form' => array(
      'callback' => 'bulk_file_upload_add_taxonomy_term_form',
      'callback arguments' => array('tid'),
    ),
    'bulk_upload_files_form' => array(
      'callback' => 'bulk_file_upload_add_files_form',
      'callback arguments' => array('tid'),
    )
  );
}

/**
 * Helper function.
 * @param int $tid: The term id of the source folder whose subfolders you want displayed.
 * @return string: An html structure of the rendered subfolders.
 */
function bulk_file_upload_render_child_folders($tid) {
  
  $html = '';
  $folder = taxonomy_term_load($tid);
  $subfolders = taxonomy_get_children($tid);

  // Display Subfolders.
  if (!empty($subfolders)) {

    $html .= '<div class="taxonomy-subfolders">';
    $html .= '<h3>' . t('Folders within @folder_name', array('@folder_name' => $folder->name)) . ':</h3>';
    $html .= '<ul>';

    usort($subfolders, "bulk_file_upload_sort_child_folders");

    foreach ($subfolders as $folder_id => $subfolder) {
      $html .= '<li>';
      $html .=  '<a href="/' . drupal_lookup_path('alias', 'taxonomy/term/' .$subfolder->tid) . '">' . 
                                '<img src="/' . drupal_get_path('module', 'bulk_file_upload') . '/img/folder-open.png" />' .
                                '<span>' . $subfolder->name . '</span></a>';
      $html .= '</li>';
    }

    $html .= '</ul>';
    $html .= '</div>';
  }
  
  return $html;
}

/**
 * Helper function.
 * @param int $tid: The term id of the source folder whose files you want displayed.
 * @return string: An html (table) of the rendered file list.
 */
function bulk_file_upload_render_file_table($tid) {
  
  $html = '';
  
  $folder = taxonomy_term_load($tid);
  $file_query = new EntityFieldQuery();
  $file_results = $file_query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'file')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_file_category', 'tid', $tid)
    ->propertyOrderBy('title')
    ->execute();
  
  $subfolders = taxonomy_get_children($tid);
  
  if (!empty($file_results) || !empty($subfolders)) {
    $html .= '<div class="taxonomy-files">';
    $html .= '<h3>' . t('Files and folders in @folder_name', array('@folder_name' => $folder->name)) . ':</h3>';
    
    if (user_access('bulk download file archive')) {
      $html .= '<a id="bulk-file-download" href="/bulk-download-files?tid=' . $tid . '" class="btn btn-small">' . t('Download All') . '</a>';
    }
    
    $html .= '<table><tr><th>' . t('Title') . '</th><th>' . t('Link') . '</th><th>' . t('File Size') . '</th><th>' . t('Last Modified By') . '</tr>';

    foreach ($subfolders as $subfolder) {
      $html .= '<tr class="folder-section">';
      $html .= '<td>' .
                 '<a href="/' . drupal_lookup_path('alias', 'taxonomy/term/' .$subfolder->tid) . '">' . 
                   '<img class="bulk-upload-folder-icon" src="/' . drupal_get_path('module', 'bulk_file_upload') . '/img/folder-open.png" />' .
                   $subfolder->name . 
                 '</a>' .
               '</td>';
      $html .= '<td></td><td></td><td></td>';
      $html .= '</tr>';
    }
    
    $file_nodes = array();
    if (!empty($file_results)) {
      $file_nodes = node_load_multiple(array_keys($file_results['node']));
    }
    
    foreach ($file_nodes as $file_node) {
      
      $file_downloads = field_get_items('node', $file_node, 'field_uploaded_file');
      
      if ($file_downloads != FALSE) {
        $html .= '<tr>';
        $html .= '<td>' .
                    '<a href="/' . drupal_get_path_alias('node/' . $file_node->nid) . '">' .
                      theme_file_icon(
                        array(
                          'file' => file_load($file_downloads[0]['fid']),
                          'icon_directory' => drupal_get_path('module', 'file') . '/icons',
                        )
                      ) .
                      $file_node->title . 
                    '</a>' .
                  '</td>';
        $html .= '<td><a download href="' . file_create_url($file_downloads[0]['uri']) . '">' . t('Download This File') . '</a></td>';
        $html .= '<td>' . format_size($file_downloads[0]['filesize']) . '</td>';
        $revision_user = user_load($file_node->revision_uid);
      
        if ($revision_user !== FALSE) {
          $html .= '<td>' . $revision_user->realname . '</td>';
        }

        $html .= '</tr>';
      }
    }

    $html .= '</table>';
    $html .= '</div>';
  }
  else {
    $html .= '<div class="messages warning">' . t('This folder has no files or folders in it.') . '</div>';
  }
  
  return $html;
}

/**
 * Helper Function.
 * Updates the items of the file breadcrumb.
 * @param type $term: A term object.
 */
function bulk_file_upload_update_breakcrumb_on_taxonomy_page($term) {
  
  if (isset($_SESSION['bulk_file_upload_breadcrumb'])) {
    // Setting up breadcrumb.
    $child_folders = taxonomy_get_children($term->tid);
    $ancestor_folders = taxonomy_get_parents_all($term->tid);
    $ancestor_term_ids = array();
    foreach ($ancestor_folders as $ancestor_folder) {
      $ancestor_term_ids[] = $ancestor_folder->tid;
    }

    $kept_breadcrumbs = array();
    foreach ($_SESSION['bulk_file_upload_breadcrumb'] as $breadcrumb_item) {

      $keep_item = TRUE;

      if (in_array($breadcrumb_item['tid'], array_keys($child_folders))) {
        $keep_item = FALSE;
      }
      else if ($breadcrumb_item['tid'] == $term->tid) {
        $keep_item = FALSE;
      }
      else if ($breadcrumb_item['tid'] != '-1' && !in_array($breadcrumb_item['tid'], $ancestor_term_ids)) {
        $keep_item = FALSE;
      }

      if ($keep_item == TRUE) {
        $kept_breadcrumbs[] = $breadcrumb_item;
      }
    }

    $_SESSION['bulk_file_upload_breadcrumb'] = $kept_breadcrumbs;

    array_push($_SESSION['bulk_file_upload_breadcrumb'], 
      array(
        'page_title' => drupal_get_title(),
        'path' => drupal_get_path_alias(current_path()),
        'type' => 'taxonomy',
        'tid' => $term->tid,
      )
    );
  }
}

/**
 * Helper Function.
 * Renders the file breadcrumb.
 * @return string: The html structure of the breadcrumb.
 */
function bulk_file_upload_render_file_breadcrumb() {
  
  $html = '';
  
  if (isset($_SESSION['bulk_file_upload_breadcrumb'])) {
    
    $should_remove_last = FALSE;
    
    if (arg(0)=='taxonomy' && arg(1)=='term') {
      $term = taxonomy_term_load(arg(2));
    
      if ($term->vocabulary_machine_name == 'file_categories') {
        $should_remove_last = TRUE;
      }
    }
    
    $html .= '<ul class="file-breadcrumb">';
    $i = 0;
    
    foreach($_SESSION['bulk_file_upload_breadcrumb'] as $breadcrumb) {
      if (($should_remove_last == TRUE && ++$i < count($_SESSION['bulk_file_upload_breadcrumb'])) || $should_remove_last == FALSE) {
        $html .= '<li><a href="/' . $breadcrumb['path'] . '">' . $breadcrumb['page_title'] . '</a></li>' . ' » ';
      }
      
    }
    
    $html = substr($html,0, -3);
    $html .= '</ul>';
  }
  
  return $html;
}